version: '3'

services:
  database:
    container_name: 'maiself-database'
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maiself
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    restart: unless-stopped
